# For developing stage
version: '3'

services:
  # The application
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - ./:/usr/app
    ports:
      - "3000:3000"
    links:      
      - mongo
      - redis
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # Database
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=kong$
      - MONGO_INITDB_DATABASE=roles
    ports:
      - "27017:27017"
    command: --auth
    #volumes:
      #- /data/mongodb:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  #Cache
  redis:
    image: redis:latest
    command: redis-server --requirepass "kong$"
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        